name: prettify
description: Beautify the code snippets in your web page
version: 0.2.1

author: Mike Mitterer <office@mikemitterer.at>
homepage: http://prettify.mikemitterer.at/

dependencies:
#  browser: any

dev_dependencies:
  test: any
  grinder: any

  logging: any
  logging_handlers: any
  console_log_handler: any

  args: any

