name: prettify
description: Beautify the code snippets in your web page
version: 0.0.1

author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/dart-prettify

dependencies:
#  browser: any

dev_dependencies:
  unittest: any
