name: prettify
description: Beautify the code snippets in your web page
version: 0.3.9

author: Mike Mitterer <office@mikemitterer.at>
homepage: http://prettify.mikemitterer.at/

environment:
  sdk: ">=2.0.0 <3.0.0"

# dependencies:
#    browser: any

dev_dependencies:
  test: any
  grinder: any

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=1.1.0 <2.0.0'
      # git: git@github.com:MikeMitterer/dart-console_log_handler.git
      # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  args: any

  build_runner: any
  build_test: any
  build_web_compilers: any

