name: usage
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  prettify:
    path: ../..

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0

  m4d_components: '>=0.1.0 <1.0.0'
  # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_components

dev_dependencies:
  build_runner: any
  build_web_compilers: any


