name: usage
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  prettify:
    path: ../..

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'

  mdl: # '>=2.1.4 <3.0.0'
    git:
     url: git@github.com:MikeMitterer/dart-material-design-lite.git
     ref: v2.2
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.4.0


