name: usage
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  prettify:
    path: ../..

  mdl: ^1.0.0

  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.1.0

  dart_to_js_script_rewriter: ^0.1.0

  di: ^3.3.0

transformers:
  - di
  - dart_to_js_script_rewriter


