name: usage
version: 0.0.1
description: An absolute bare-bones web app.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: any

  prettify:
    path: ../..

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: '>=0.5.0 <1.0.0'

  mdl: # '>=2.1.4 <3.0.0'
    git:
     url: git@github.com:MikeMitterer/dart-material-design-lite.git
     ref: v2.2
    # path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite

dev_dependencies:

  dart_to_js_script_rewriter: ^0.1.0

transformers:
  - dart_to_js_script_rewriter


